// Aqui temos um array....
const fabricantes = ['Mercedes', 'Audi', 'BMW']

// Função que imprime o indice e nome do array...
function imprimir(nome, indice) {
    console.log(`${indice}. ${nome}`)
}

// Chamamos o array com foreach e passamos por parâmetro a função imprimir...
fabricantes.forEach(imprimir)
// Aqui imprimimos os nomes do array...
fabricantes.forEach(fabricante => console.log(fabricante))