const pilotos = ['Vettel', 'Alonso', 'Senna', 'Hamilton']
pilotos.pop() // Massa quebrou o carro e saiu da lista de pilotos, pop remove ultimo elemento do array...
console.log(pilotos)

pilotos.push('Vestappen') // push Adiciona um novo elemento no array.....
console.log(pilotos)


pilotos.shift() // shift igual pop , mas remove o primeiro elemnto e não o ultimo...
console.log(pilotos)

pilotos.unshift('Raikonnen')// Igual o push , adiciona um elemento no array, mais na primeira posição e não na ultima...


//splice pode adicionar e remover elementos...

// Adicionar elementos...
pilotos.splice(2, 0, 'Bottas', 'Massa') // adiciona antes do elemento dois...
console.log(pilotos)

// Remover elementos...
pilotos.splice(3, 1) // Removeu o indice 3 que seria o Massa...
console.log(pilotos)

const algunsPilotos1 = pilotos.slice(2) // Retorna um novo array pegando a partir do indice 2 do array de pilotos...
console.log(algunsPilotos1)

// Aqui podemos pegar um pedaço do array, rotorna do indice 1 até o 3, o 4 não está incluso 
const algunsPilotos2 = pilotos.slice(1, 4)
console.log(algunsPilotos2)