// não inicializada...
let valor 
// Imprimindo variável...
console.log(valor)
// null ausência de valor...
valor = null 
// Imprimindo variável...
console.log(valor)

// Erro...
//console.log(valor.toString())

// criamos um objeto produto vazio
const produto = {}
// Aqui retorna undefined,porque o atributo preço nao foi definido...
console.log(produto.preco)
// Aqui retorna objeto vazio...
console.log(produto)
// aqui atribuimos um valor ao atributo preco...
produto.preco = 45.50
// Imprimindo novamente e retornara o valor do preço e nao undefined...
console.log(produto)
// evite atribuir undefined 
produto.preco = undefined 
// imprimindo com retorno boolean, neste caso retorna false por ser undefined...
console.log(!!produto.preco)
// Imprimindo o objeto novamente...
console.log(produto)
// Dizendo que o produto está sem preço 
produto.preco = null
// imprimindo com retorno boolean, neste caso retorna false por ser null...
console.log(!!produto.preco)
// Imprimindo o objeto novamente...
console.log(produto)
