// Retorna Infinity...
console.log(7 / 0)
// Aqui o resultado será '5' ele converte a string em number e  divide por 2....
console.log('10' / 2)
// Aqui a string tem preferencia então vai ser contatenado e resultado será '32'...
console.log("3" + 2)
// Aqui ele retorna um 'NaN' notificando que 'Show' não é um número...
console.log('Show!!!' * 2)
// Gera uma pequena imprecisão de calcúlo...
console.log(0.1 + 0.7)
//console.log(10.toString())  Aqui da erro, mas se colocarmos o 10 entre parente funciona normal!!!
console.log((10).toString()) 