console.log(7 / 0) // Retorna Infinity...
console.log('10' / 2)
console.log('Show!!!' * 2)
console.log(0.1 + 0.7) // Gera uma pequena imprecisão de calcúlo...
//console.log(10.toString())  Aqui da erro, mas se colocarmos o 10 entre parente funciona normal!!!
console.log((10).toString()) 