// Aqui retorna true independente de ser tipos diferentes (string == number)...
console.log('01)', '1' == 1)
/* Quando se usa 3 iguais '===', ele comse e emtritamente igual , 
então o retorno será falso porque são tipos diferentes...*/
console.log('02)', '1' === 1)
// Aqui a mesma coisa, indepedente de tipos ele compara , e retorna false....
console.log('03)', '3' != 3)
// Aqui retorna true porque e explicito a comparação, sao de diferentes tipos...
console.log('04)', '3' !== 3)

// AQui retorna false poruqe 3 não é menor 2...
console.log('05)', 3 < 2)
// Aqui retorna true porque 3 é maior que 2...
console.log('06)', 3 > 2)
// Aqui retorna true poruqe 3 é igual ou menor a 3...
console.log('07)', 3 <= 3)
// Aqui retorna true porque 2 e maior ou igual a 2...
console.log('08)', 2 >= 2)

const d1 = new Date(0)
const d2 = new Date(0)
// Aqui no objeto retorna false porque ele compara endereço de memória e não valores...
console.log('09)', d1 == d2)
// Aqui o retorno e true porque o getDate compara os valores e não endereço de memória...
console.log('10)', d1.getDate == d2.getDate)
// Aqui retorna true, pois tem o mesmo valor...
console.log('11)', undefined == null)
// Aqui e false pq a comparação e extrita, diferente tipos retorna false...
console.log('12)', undefined === null)
