const escola = "Cod3r"
// Essa função retorna o indíce da string no caso 'r'....
console.log(escola.charAt(4))
// Aqui ele pede o indice 5 que não existe na variável, o retorno e vazio...
console.log(escola.charAt(5))
// Retorna o indice 3 com o valor dentro tabela ask ou unicode....
console.log(escola.charCodeAt(3))
// Aqui retorna o indice onde se encontra o caractere '3'.....
console.log(escola.indexOf('3'))
// Aqui ele retorna o resto da string a partir do indice declarado '1' e imprime o restante....
console.log(escola.substring(1))
// Aqui ele retorna os indices'0' até '2'.....
console.log(escola.substring(0,3))
// Aqui é como se contatena em javascript
console.log('Escola '.concat(escola).concat("!"))
// Aqui ele aplica um replace, chama o indice '3' e faz a substituição por 'e'...
console.log(escola.replace(3, 'e'))
// Aqui aplicando a função split ele gera um array com a virgula separando seus elementos...
console.log('Ana,Maria,Pedro'.split(','))